language: php

notifications:
  email:
    on_success: never

git:
  depth: 2

matrix:
  include:
    - php: hhvm
    - php: nightly
    - php: 7.2
      env:
      - LINT=true
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction

script:
  - if [[ $LINT = true ]]; then
      composer cs-lint;
    fi
  - composer test
